### ISSUE TITLE
Izboljšajta opis igrice

### ISSUE THREAD

**Issue by andrejbauer** [Migelo/nameUnknown#1]
Opis igrice je premalo podroben, da bi razumel, točno kako bo to delovalo. Fino bi bilo, če bi bila kaka slikica, ki jo lahko v Markdown enostavno naredita takole:

    +---+---+---+---+---+---+---+
    | X | X |   |   |   |   |   |
    +---+---+---+---+---+---+---+
    |   |   |   |   |   |   |   |
    +---+---+---+---+---+---+---+
    |   |   |   |   |   |   |   |
    +---+---+---+---+---+---+---+
    |   |   |   |   |   | O |   |
    +---+---+---+---+---+---+---+
    |   |   |   |   |   | O | O |
    +---+---+---+---+---+---+---+

(Zgornjo razpredelnico sem najprej naredil v urejevalniku besedila s fontom fiksne širine.) Ni treba, da so navodila igrice ful lepa, morajo pa biti razumljiva. Pa morda kak naslov v `README.md` itd.

Sicer je pa igrica primernega tipa.

**Comment by Migelo** [comment]
Opis igrice urejen. #3
